### ISSUE TITLE
feature request: camera matrices as public member variables of Camera?

### ISSUE THREAD

**Issue by Aravind-Sundararajan** [Gizmo199/fauxton3D#3]
it looks like currently these are locally scoped in camera_update() using var, but maybe people want to use these to project things without building twice. not too sure if this will cause problems

**Comment by Gizmo199** [comment]
Hey thanks for the suggestion! I really need to do a camera overhaul for
sure.and it wouldn't cause any problems at all! You can make them local if
you wish and it shouldn't mess with anything. :)

**Comment by Aravind-Sundararajan** [comment]
Thanks for the reply. I'm playing with a couple things since last time, largely dealing with the html5 release and how tile layers are drawn and some minor things like automating the scaling of fauxton_texcubes. what I've hacked together right now is to render tile layers to surfaces otherwise you get strange disappearing tiles. If I think I have any considerable changes, I'll make a pull request

**Comment by Gizmo199** [comment]
Sounds good. Yeah GMs internal tile system doesn't work well with
orthogtaphic cameras when rotated/ pitched since GM internally occluded
pixels outside the fulcrum. I think perspective cameras work though. Anywho
glad you got some stuff working! I am working on some shadow casting stuff
now so hopefully in the future that can be implemented.:)
